
CREATE DATABASE PROJOURNEY;
USE PROJOURNEY;

CREATE TABLE PJ_ALUNO (
  ID INT NOT NULL AUTO_INCREMENT,
  nome VARCHAR(60) NOT NULL,
  email VARCHAR(100) NOT NULL,
  idade INT NOT NULL,
  telefone VARCHAR(11) NOT NULL,
  cidade VARCHAR(100) NULL,
  descricao VARCHAR(500) NULL,
  area_interesse VARCHAR(100) NULL,
  senha VARCHAR(300) NOT NULL,
  PRIMARY KEY (ID)
);


CREATE TABLE PJ_TRILHA (
  ID INT NOT NULL AUTO_INCREMENT,
  nome VARCHAR(100) NOT NULL,
  PRIMARY KEY (ID)
);


CREATE TABLE PJ_PROGRESSO (
  ID INT NOT NULL AUTO_INCREMENT,
  progresso ENUM('Não inscrito', 'Cursando', 'Concluido') NOT NULL,
  PRIMARY KEY (ID)
);


CREATE TABLE PJ_TRILHA_ALUNO_PROGRESSO (
  PJ_TRILHA_ID INT NOT NULL,
  PJ_ALUNO_ID INT NOT NULL,
  PJ_PROGRESSO_ID INT NOT NULL,
  PRIMARY KEY (PJ_TRILHA_ID, PJ_ALUNO_ID, PJ_PROGRESSO_ID),
  FOREIGN KEY (PJ_TRILHA_ID) REFERENCES PJ_TRILHA (ID),
  FOREIGN KEY (PJ_ALUNO_ID) REFERENCES PJ_ALUNO (ID)
    ON DELETE CASCADE
    ON UPDATE RESTRICT,
  FOREIGN KEY (PJ_PROGRESSO_ID) REFERENCES PJ_PROGRESSO (ID)
);


CREATE TABLE PJ_EXPERIENCIA (
  ID INT NOT NULL AUTO_INCREMENT,
  nome VARCHAR(100) NOT NULL,
  PRIMARY KEY (ID)
);


CREATE TABLE PJ_ALUNO_EXPERIENCIA (
  PJ_EXPERIENCIA_ID INT NOT NULL,
  PJ_ALUNO_ID INT NOT NULL,
  PRIMARY KEY (PJ_EXPERIENCIA_ID, PJ_ALUNO_ID),
  FOREIGN KEY (PJ_EXPERIENCIA_ID) REFERENCES PJ_EXPERIENCIA (ID),
  FOREIGN KEY (PJ_ALUNO_ID) REFERENCES PJ_ALUNO (ID)
      ON DELETE CASCADE 
      ON UPDATE RESTRICT
);


CREATE TABLE PJ_CURSO (
  ID INT NOT NULL AUTO_INCREMENT,
  nome VARCHAR(150) NOT NULL,
  nivel ENUM('Basico', 'Intermediario', 'Avançado') NOT NULL,
  link_curso VARCHAR(255) NOT NULL,
  PRIMARY KEY (ID)
);


CREATE TABLE PJ_CURSO_TRILHA (
  PJ_CURSO_ID INT NOT NULL,
  PJ_TRILHA_ID INT NOT NULL,
  PRIMARY KEY (PJ_CURSO_ID, PJ_TRILHA_ID),
  FOREIGN KEY (PJ_CURSO_ID) REFERENCES PJ_CURSO (ID), 
  FOREIGN KEY (PJ_TRILHA_ID) REFERENCES PJ_TRILHA (ID)
);

